# -*- coding: utf-8 -*-
"""JudiOnline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TzYPeUlBw4USaqlKWUgvgLReB8PQQim

##Twitter Auth Token
"""

#@title Twitter Auth Token

twitter_auth_token = '980d6a1d4d2ba3aff4417273a41de093ce6328ef'

#Crawling Data Tweet 2000 Tweets"""

# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Crawl Data

filename = 'judionlin6.csv'
search_keyword = 'korban judi online lang:id'
limit = 400

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd

file_path = f"tweets-data/{filename}"

df = pd.read_csv(file_path, delimiter=",")

display(df)

#PREPROCESSING DATA

#Mengecek duplikat kata dalam dataframe

df = pd.read_csv("cleaned_judionlinetweets.csv")

df.head()

# Mengecek duplikat berdasarkan kolom 'tweet_text'
duplicate_text = df[df.duplicated('text')]

print("\nDuplikat berdasarkan kolom 'tweet_text':")
print(duplicate_text)

df_no_duplicates = df.drop_duplicates('text')

print("\nDataFrame setelah menghapus duplikat berdasarkan kolom 'tweet_id':")
print(df_no_duplicates)

df_no_duplicates.to_csv('cleaned_judionlinetweets.csv', index=False)

#PREPROCESSING DATA

#CLEANING DATA

import pandas as pd
import numpy as np

!pip install unidecode
!pip install contractions
!pip install demoji
!pip install num2words
!pip install SpellChecker

import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string
import demoji
import contractions
import unidecode
from num2words import num2words
from nltk.corpus import twitter_samples
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer
from bs4 import BeautifulSoup

df = pd.read_csv("JudiOnline.csv")

df.head()

print(f'Shape of the whole data is: {df.shape[0]} rows and {df.shape[1]} columns')

#Membuang kolom yang tidak dibutuhkan

#drop kolom yang tidak dibutuhkan (index kolom dimulai dari nol)
df.drop(df.columns[[0,2,4,5,6,7,8,9,10,11,12,13]], axis=1, inplace=True)

display(df)

#Lower casing

df.text = df.text.str.lower()
df.head(20)

#URL

df.text = df.text.str.replace(r'https?://\S+|www\.\S+', '', regex=True)
df.head(20)

#Hashtag & mentions

def remove_tags_mentions(text):
    pattern = re.compile(r'(@\S+|#\S+)')
    return pattern.sub('', text)

df.text = df.text.apply(lambda x: remove_tags_mentions(x))

df.head(20)

#Punctuations

PUNCTUATIONS = string.punctuation

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCTUATIONS))


df.text = df["text"].apply(lambda text: remove_punctuation(text))

df.head(20)

#Emoticon

#collapse-hide

EMOTICONS = {
    u":‑\)":"Happy face or smiley",
    u":\)":"Happy face or smiley",
    u":-\]":"Happy face or smiley",
    u":\]":"Happy face or smiley",
    u":-3":"Happy face smiley",
    u":3":"Happy face smiley",
    u":->":"Happy face smiley",
    u":>":"Happy face smiley",
    u"8-\)":"Happy face smiley",
    u":o\)":"Happy face smiley",
    u":-\}":"Happy face smiley",
    u":\}":"Happy face smiley",
    u":-\)":"Happy face smiley",
    u":c\)":"Happy face smiley",
    u":\^\)":"Happy face smiley",
    u"=\]":"Happy face smiley",
    u"=\)":"Happy face smiley",
    u":‑D":"Laughing, big grin or laugh with glasses",
    u":D":"Laughing, big grin or laugh with glasses",
    u"8‑D":"Laughing, big grin or laugh with glasses",
    u"8D":"Laughing, big grin or laugh with glasses",
    u"X‑D":"Laughing, big grin or laugh with glasses",
    u"XD":"Laughing, big grin or laugh with glasses",
    u"=D":"Laughing, big grin or laugh with glasses",
    u"=3":"Laughing, big grin or laugh with glasses",
    u"B\^D":"Laughing, big grin or laugh with glasses",
    u":-\)\)":"Very happy",
    u":‑\(":"Frown, sad, andry or pouting",
    u":-\(":"Frown, sad, andry or pouting",
    u":\(":"Frown, sad, andry or pouting",
    u":‑c":"Frown, sad, andry or pouting",
    u":c":"Frown, sad, andry or pouting",
    u":‑<":"Frown, sad, andry or pouting",
    u":<":"Frown, sad, andry or pouting",
    u":‑\[":"Frown, sad, andry or pouting",
    u":\[":"Frown, sad, andry or pouting",
    u":-\|\|":"Frown, sad, andry or pouting",
    u">:\[":"Frown, sad, andry or pouting",
    u":\{":"Frown, sad, andry or pouting",
    u":@":"Frown, sad, andry or pouting",
    u">:\(":"Frown, sad, andry or pouting",
    u":'‑\(":"Crying",
    u":'\(":"Crying",
    u":'‑\)":"Tears of happiness",
    u":'\)":"Tears of happiness",
    u"D‑':":"Horror",
    u"D:<":"Disgust",
    u"D:":"Sadness",
    u"D8":"Great dismay",
    u"D;":"Great dismay",
    u"D=":"Great dismay",
    u"DX":"Great dismay",
    u":‑O":"Surprise",
    u":O":"Surprise",
    u":‑o":"Surprise",
    u":o":"Surprise",
    u":-0":"Shock",
    u"8‑0":"Yawn",
    u">:O":"Yawn",
    u":-\*":"Kiss",
    u":\*":"Kiss",
    u":X":"Kiss",
    u";‑\)":"Wink or smirk",
    u";\)":"Wink or smirk",
    u"\*-\)":"Wink or smirk",
    u"\*\)":"Wink or smirk",
    u";‑\]":"Wink or smirk",
    u";\]":"Wink or smirk",
    u";\^\)":"Wink or smirk",
    u":‑,":"Wink or smirk",
    u";D":"Wink or smirk",
    u":‑P":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u":P":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u"X‑P":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u"XP":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u":‑Þ":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u":Þ":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u":b":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u"d:":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u"=p":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u">:P":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u":‑/":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u":/":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u":-[.]":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u">:[(\\\)]":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u">:/":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u":[(\\\)]":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u"=/":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u"=[(\\\)]":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u":L":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u"=L":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u":S":"Skeptical, annoyed, undecided, uneasy or hesitant",
    u":‑\|":"Straight face",
    u":\|":"Straight face",
    u":$":"Embarrassed or blushing",
    u":‑x":"Sealed lips or wearing braces or tongue-tied",
    u":x":"Sealed lips or wearing braces or tongue-tied",
    u":‑#":"Sealed lips or wearing braces or tongue-tied",
    u":#":"Sealed lips or wearing braces or tongue-tied",
    u":‑&":"Sealed lips or wearing braces or tongue-tied",
    u":&":"Sealed lips or wearing braces or tongue-tied",
    u"O:‑\)":"Angel, saint or innocent",
    u"O:\)":"Angel, saint or innocent",
    u"0:‑3":"Angel, saint or innocent",
    u"0:3":"Angel, saint or innocent",
    u"0:‑\)":"Angel, saint or innocent",
    u"0:\)":"Angel, saint or innocent",
    u":‑b":"Tongue sticking out, cheeky, playful or blowing a raspberry",
    u"0;\^\)":"Angel, saint or innocent",
    u">:‑\)":"Evil or devilish",
    u">:\)":"Evil or devilish",
    u"\}:‑\)":"Evil or devilish",
    u"\}:\)":"Evil or devilish",
    u"3:‑\)":"Evil or devilish",
    u"3:\)":"Evil or devilish",
    u">;\)":"Evil or devilish",
    u"\|;‑\)":"Cool",
    u"\|‑O":"Bored",
    u":‑J":"Tongue-in-cheek",
    u"#‑\)":"Party all night",
    u"%‑\)":"Drunk or confused",
    u"%\)":"Drunk or confused",
    u":-###..":"Being sick",
    u":###..":"Being sick",
    u"<:‑\|":"Dump",
    u"\(>_<\)":"Troubled",
    u"\(>_<\)>":"Troubled",
    u"\(';'\)":"Baby",
    u"\(\^\^>``":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    u"\(\^_\^;\)":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    u"\(-_-;\)":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    u"\(~_~;\) \(・\.・;\)":"Nervous or Embarrassed or Troubled or Shy or Sweat drop",
    u"\(-_-\)zzz":"Sleeping",
    u"\(\^_-\)":"Wink",
    u"\(\(\+_\+\)\)":"Confused",
    u"\(\+o\+\)":"Confused",
    u"\(o\|o\)":"Ultraman",
    u"\^_\^":"Joyful",
    u"\(\^_\^\)/":"Joyful",
    u"\(\^O\^\)／":"Joyful",
    u"\(\^o\^\)／":"Joyful",
    u"\(__\)":"Kowtow as a sign of respect, or dogeza for apology",
    u"_\(\._\.\)_":"Kowtow as a sign of respect, or dogeza for apology",
    u"<\(_ _\)>":"Kowtow as a sign of respect, or dogeza for apology",
    u"<m\(__\)m>":"Kowtow as a sign of respect, or dogeza for apology",
    u"m\(__\)m":"Kowtow as a sign of respect, or dogeza for apology",
    u"m\(_ _\)m":"Kowtow as a sign of respect, or dogeza for apology",
    u"\('_'\)":"Sad or Crying",
    u"\(/_;\)":"Sad or Crying",
    u"\(T_T\) \(;_;\)":"Sad or Crying",
    u"\(;_;":"Sad of Crying",
    u"\(;_:\)":"Sad or Crying",
    u"\(;O;\)":"Sad or Crying",
    u"\(:_;\)":"Sad or Crying",
    u"\(ToT\)":"Sad or Crying",
    u";_;":"Sad or Crying",
    u";-;":"Sad or Crying",
    u";n;":"Sad or Crying",
    u";;":"Sad or Crying",
    u"Q\.Q":"Sad or Crying",
    u"T\.T":"Sad or Crying",
    u"QQ":"Sad or Crying",
    u"Q_Q":"Sad or Crying",
    u"\(-\.-\)":"Shame",
    u"\(-_-\)":"Shame",
    u"\(一一\)":"Shame",
    u"\(；一_一\)":"Shame",
    u"\(=_=\)":"Tired",
    u"\(=\^\·\^=\)":"cat",
    u"\(=\^\·\·\^=\)":"cat",
    u"=_\^=	":"cat",
    u"\(\.\.\)":"Looking down",
    u"\(\._\.\)":"Looking down",
    u"\^m\^":"Giggling with hand covering mouth",
    u"\(\・\・?":"Confusion",
    u"\(?_?\)":"Confusion",
    u">\^_\^<":"Normal Laugh",
    u"<\^!\^>":"Normal Laugh",
    u"\^/\^":"Normal Laugh",
    u"\（\*\^_\^\*）" :"Normal Laugh",
    u"\(\^<\^\) \(\^\.\^\)":"Normal Laugh",
    u"\(^\^\)":"Normal Laugh",
    u"\(\^\.\^\)":"Normal Laugh",
    u"\(\^_\^\.\)":"Normal Laugh",
    u"\(\^_\^\)":"Normal Laugh",
    u"\(\^\^\)":"Normal Laugh",
    u"\(\^J\^\)":"Normal Laugh",
    u"\(\*\^\.\^\*\)":"Normal Laugh",
    u"\(\^—\^\）":"Normal Laugh",
    u"\(#\^\.\^#\)":"Normal Laugh",
    u"\（\^—\^\）":"Waving",
    u"\(;_;\)/~~~":"Waving",
    u"\(\^\.\^\)/~~~":"Waving",
    u"\(-_-\)/~~~ \($\·\·\)/~~~":"Waving",
    u"\(T_T\)/~~~":"Waving",
    u"\(ToT\)/~~~":"Waving",
    u"\(\*\^0\^\*\)":"Excited",
    u"\(\*_\*\)":"Amazed",
    u"\(\*_\*;":"Amazed",
    u"\(\+_\+\) \(@_@\)":"Amazed",
    u"\(\*\^\^\)v":"Laughing,Cheerful",
    u"\(\^_\^\)v":"Laughing,Cheerful",
    u"\(\(d[-_-]b\)\)":"Headphones,Listening to music",
    u'\(-"-\)':"Worried",
    u"\(ーー;\)":"Worried",
    u"\(\^0_0\^\)":"Eyeglasses",
    u"\(\＾ｖ\＾\)":"Happy",
    u"\(\＾ｕ\＾\)":"Happy",
    u"\(\^\)o\(\^\)":"Happy",
    u"\(\^O\^\)":"Happy",
    u"\(\^o\^\)":"Happy",
    u"\)\^o\^\(":"Happy",
    u":O o_O":"Surprised",
    u"o_0":"Surprised",
    u"o\.O":"Surpised",
    u"\(o\.o\)":"Surprised",
    u"oO":"Surprised",
    u"\(\*￣m￣\)":"Dissatisfied",
    u"\(‘A`\)":"Snubbed or Deflated"
}

def remove_emoticons(text):
    emoticons_pattern = re.compile(u'(' + u'|'.join(emo for emo in EMOTICONS) + u')')
    return emoticons_pattern.sub(r'', text)

df.text = df.text.apply(lambda x: remove_emoticons(x))

df.head(20)

#Extra Whitespaces

def remove_whitespaces(text):
    return " ".join(text.split())

df.text = df.text.apply(lambda x: remove_whitespaces(x))
df.head(20)

#Special Characters

def remove_special_characters(text):
    # define the pattern to keep
    pat = r'[^a-zA-z0-9.,!?/:;\"\'\s]'
    return re.sub(pat, '', text)

df.text = df.text.apply(remove_special_characters)
df.head(20)

#Number

df.text = df.text.str.replace(r'\d+', '', regex=True)

df.head(20)

#Date

df.text = df.text.str.replace(r'\d{1,2}(st|nd|rd|th)?[-./]\d{1,2}[-./]\d{2,4}', '', regex=True)

df.text = df.text.str.replace(r'(\d{1,2})?(st|nd|rd|th)?[-./,]?\s?(of)?\s?([J|j]an(uary)?|[F|f]eb(ruary)?|[Mm]ar(ch)?|[Aa]pr(il)?|[Mm]ay|[Jj]un(e)?|[Jj]ul(y)?|[Aa]ug(ust)?|[Ss]ep(tember)?|[Oo]ct(ober)?|[Nn]ov(ember)?|[Dd]ec(ember)?)\s?(\d{1,2})?(st|nd|rd|th)?\s?[-./,]?\s?(\d{2,4})?', '', regex=True)

df.head(20)

"""Slang to words"""

slang_dict = {
    "yg": "yang",
    "bkn": "bukan",
    "tdk": "tidak",
    "gk": "tidak",
    "gak": "tidak",
    "ga": "tidak",
    "kpn": "kapan",
    "krn": "karena",
    "knp": "kenapa",
    "dlm": "dalam",
    "dmn": "dimana",
    "aja": "saja",
    "jg": "juga",
    "jd": "jadi",
    "brp": "berapa",
    "bgmn": "bagaimana",
    "spt": "seperti",
    "sy": "saya",
    "gw": "saya",
    "gua": "saya",
    "km": "kamu",
    "lu": "kamu",
    "lo": "kamu",
    "u": "kamu",
    "lu": "kamu",
    "loe": "kamu",
    "trs": "terus",
    "trus": "terus",
    "sbg": "sebagai",
    "sdh": "sudah",
    "udh": "sudah",
    "tlh": "telah",
    "udah": "sudah",
    "msh": "masih",
    "mshh": "masih",
    "dgn": "dengan",
    "dlm": "dalam",
    "pd": "pada",
    "utk": "untuk",
    "mksd": "maksud",
    "nya": "nya",
    "jln": "jalan",
    "tmn": "teman",
    "pgn": "ingin",
    "pngn": "ingin",
    "knp": "kenapa",
    "dr": "dari",
    "drpd": "daripada",
    "drmn": "darimana",
    "ky": "kaya",
    "kyk": "seperti",
    "sm": "sama",
    "sma": "sama",
    "cm": "cuma",
    "cuma": "hanya",
    "plg": "pulang",
    "mshh": "masih",
    "hrus": "harus",
    "lbh": "lebih",
    "aj": "saja",
    "bgt": "banget",
    "brng": "barang",
    "ngapain": "apa yang",
    "kalo": "kalau",
    "kl": "kalau",
    "tp": "tapi",
    "gimana": "bagaimana",
    "gimane": "bagaimana",
    "ga": "tidak",
    "trm": "terima",
    "kmrn": "kemarin",
    "kmn": "kemana",
    "trkdg": "terkadang",
    "drmn": "darimana",
    "mo": "mau",
    "smg": "semoga",
    "ttg": "tentang",
    "sm2": "sama-sama",
    "syng": "sayang",
    "xixixi": "tertawa",
    "gmn": "bagaimana",
    "gtu": "begitu",
    "ngeliat":  "melihat",
    "bnyk": "banyak",
    "apk": "aplikasi",
    "dpt": "dapat",
    "sono": "sana",
    "klo": "kalau",
    "jgn": "jangan",
    "jdi": "jadi"
}


def replace_slang(text, slang_dict):
    for slang, formal in slang_dict.items():
        pattern = re.compile(r'\b' + re.escape(slang) + r'\b', re.IGNORECASE)
        text = pattern.sub(formal, text)
    return text

df.text = df.text.apply(lambda x: replace_slang(x, slang_dict))
df.head(20)

#STOPWORDS

!pip install sastrawi

import nltk
from nltk.corpus import stopwords
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

nltk.download('stopwords')

stop_words_indonesian = set(stopwords.words('indonesian'))


import nltk
from nltk.corpus import stopwords

# Mengunduh daftar stopwords untuk bahasa Indonesia
nltk.download('stopwords')

# Mendapatkan stopwords untuk bahasa Indonesia
stop_words_indonesian = stopwords.words('indonesian')

# Menambahkan kata-kata tambahan ke dalam stopwords
stop_words_indonesian.extend(['x', 'org', 'nih', 'gitu', 'kok', 'sih', 'apk', 'si', 'tu', 'deh', 'jgn',
                              'di', 'klo', 'dah', 'ke', 'ya', 'lah', 'ya', 'kan', 'napa', 'dpt', 'kek',
                              'na', 'becus', 'kaga', 'tuh', 'eh', 'ko', 'mah', 'kah', 'g', 'noh', 'pmk'
                              'porn', 'nya', 'tau', 'org', 'judol', 'iya', 'juni result', 'gini', 'gue',
                              'kak', 'buud', 'jp', 'rp', 'shio ular', 'ayam', 'phk', 'loh', 'ndk', 'oh',
                              'sih', 'amp', 'sabtui', 'si', 'result shio', 'nya', 'ya', 'tu', 'si', 'ke',
                              'nya', 'pak'])

# Menampilkan stopwords Indonesia yang sudah diperbarui
#print(stop_words_indonesian)

factory = StopWordRemoverFactory()
stopword_remover = factory.create_stop_word_remover()

def remove_stop_words(text):
    words = text.split()
    cleaned_words = [word for word in words if word.lower() not in stop_words_indonesian]
    return ' '.join(cleaned_words)

df['tweet_stopwords'] = df['text'].apply(remove_stop_words)

df.head()

#TOKENIZATION

from nltk.tokenize import word_tokenize

nltk.download('punkt')

# Fungsi untuk tokenisasi teks
def tokenize_text(text):
    tokens = word_tokenize(text)
    return tokens

# Terapkan fungsi ke kolom 'tweet_text'
df['tokenized_text'] = df['text'].apply(tokenize_text)

df.head()

#STEMMING

import re
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_text(text):
    # Tokenization and Stemming
    tokens = text.split()
    stemmed_tokens = [stemmer.stem(token) for token in tokens]
    # Menggabungkan kembali token yang telah di-stem
    return ' '.join(stemmed_tokens)

# Terapkan fungsi ke kolom 'tweet_text'
df['stemmed_text'] = df['text'].apply(stem_text)

df.head(10)

df.to_csv('judionlinecleaning4.csv', index=False)

#LABELING

import pandas as pd
import os
import json
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
# Nama file CSV
base = "/content/judionlinecleaning4.csv"

# Membaca DataFrame dari file CSV
Corpus = pd.read_csv(base, encoding='utf8')

# Inisialisasi VADER Sentiment Analyzer
sia1A, sia1B, sia2 = SentimentIntensityAnalyzer(), SentimentIntensityAnalyzer(), SentimentIntensityAnalyzer()

# Bersihkan leksikon VADER default
sia1A.lexicon.clear()
sia1B.lexicon.clear()
sia2.lexicon.clear()

# # Membaca leksikon InSet
# with open('/content/_json_inset-neg.txt') as f:
#     data1A = f.read()
# with open('/content/_json_inset-pos.txt') as f:
#     data1B = f.read()

#Membaca leksikon sentiwords_id
with open('/content/_json_sentiwords_id.txt') as f:
    data2 = f.read()

# Ubah leksikon menjadi dictionary
senti = json.loads(data2)

# Update leksikon VADER
sia2.lexicon.update(senti)

print("Lexicons updated.")

# # Fungsi untuk menentukan label positif/negatif berdasarkan skor compound dari VADER
# def is_positive_inset(tweet: str) -> bool:
#     """True if tweet has positive compound sentiment, False otherwise."""
#     return sia1A.polarity_scores(tweet)["compound"] + sia1B.polarity_scores(tweet)["compound"] > 0

def is_positive_senti(tweet: str) -> bool:
    """True if tweet has positive compound sentiment, False otherwise."""
    return sia2.polarity_scores(tweet)["compound"] > 0

# Menyimpan teks dari Corpus
tweets = Corpus["text"]

# # Menulis hasil klasifikasi label untuk setiap kalimat berdasarkan nilai compound dari insetNeg dan insetPos
# output_inset = os.path.splitext(base)[0] + '-lb-inset.txt'
# with open(output_inset, 'w') as f:
#     for tweet in tweets:
#         if is_positive_inset(tweet):
#             label = "positif"
#         else:
#             label = "negatif"
#         f.write(str(label) + '\n')

# print("Saved labels based on insetNeg and insetPos to:", output_inset)

# Menulis hasil klasifikasi label untuk setiap kalimat berdasarkan nilai compound dari sentiwords_id
output_senti = os.path.splitext(base)[0] + '-lb-senti.txt'
with open(output_senti, 'w') as f:
    for tweet in tweets:
        if is_positive_senti(tweet):
            label = "positif"
        else:
            label = "negatif"
        f.write(str(label) + '\n')

print("Saved labels based on sentiwords_id to:", output_senti)

# # Membaca hasil klasifikasi label dari file teks inset
# with open(output_inset, 'r') as f:
#     labels_inset = f.readlines()

# Membaca hasil klasifikasi label dari file teks senti
with open(output_senti, 'r') as f:
    labels_senti = f.readlines()

# Menggabungkan hasil label dari kedua metode ke dalam DataFrame
#Corpus['label_inset'] = [label.strip() for label in labels_inset]
Corpus['label_senti'] = [label.strip() for label in labels_senti]

# Menyimpan DataFrame ke file CSV dengan kolom baru label
output_with_label = os.path.splitext(base)[0] + '-with-label3.csv'
Corpus.to_csv(output_with_label, index=False)

print("Saved labeled data to:", output_with_label)

df = pd.read_csv('/content/judionlinecleaning4-with-label3.csv')
df.head(20)

print(f'Shape of the whole data is: {df.shape[0]} rows and {df.shape[1]} columns')

label_counts = df['label_senti'].value_counts()
print(label_counts)

import matplotlib.pyplot as plt
grouped = df.groupby(['label_senti']); grouped.size().plot(kind='bar')
plt.show()

#VISUALISASI

#VISUALISASI STOPWORDS
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Function to create and display a word cloud
def create_word_cloud(stemmed_text):
    wordcloud = WordCloud(width=800, height=400, background_color='black').generate(stemmed_text)
    plt.figure(figsize=(15, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.show()

# Combine all rows into a single string for each column
Text_combined = ''.join(df['stemmed_text'].astype(str))

# Create and display word clouds
create_word_cloud(Text_combined)

#df_positive = df[df['label_senti'] == 'positive']
#df_negative = df[df['label_senti'] == 'negative']

#VISUALISASI UNTUK LABELING POSITIF
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Membaca data dari file CSV
df = pd.read_csv('/content/judionlinecleaning4-with-label3.csv')

# Memilih data dengan label positif
df_positive = df[df['stemmed_text'] == 'stemmed_text']

df_positive = df[df['label_senti'] == 'positif']

# Memastikan bahwa kolom 'text' dalam DataFrame adalah string
df_positive['text'] = df_positive['text'].astype(str)

# Menggabungkan semua teks dalam kolom 'text' menjadi satu string besar
positive_texts = ' '.join(df_positive['stemmed_text'])

# Membuat word cloud
wordcloud = WordCloud(width=800, height=400, background_color='black').generate(positive_texts)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

#VISUALISASI UNTUK LABELING NEGATIF
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Membaca data dari file CSV
df = pd.read_csv('/content/judionlinecleaning4-with-label3.csv')

# Memilih data dengan label negative
df_negative = df[df['label_senti'] == 'negatif']

# Memastikan bahwa kolom 'text' dalam DataFrame adalah string
df_negative['stemmed_text'] = df_negative['stemmed_text'].astype(str)

# Menggabungkan semua teks dalam kolom 'text' menjadi satu string besar
negative_texts = ' '.join(df_negative['stemmed_text'])

# Membuat word cloud
wordcloud = WordCloud(width=800, height=400, background_color='black').generate(negative_texts)

# Menampilkan word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

#TF-IDF

df = pd.read_csv('judionlinecleaning4-with-label3.csv')
df.head()

import numpy as np
import pandas as pd

# Tokenize and generate count vectors
word_vec = df['text'].apply(lambda x: pd.value_counts(x.split())).fillna(0)

word_vec

tf = word_vec.divide(word_vec.sum(axis=1), axis=0)

tf

idf = np.log10(len(tf) / word_vec[word_vec > 0].count() + 1)

idf

# Compute TF-IDF vectors
#tfidf = np.multiply(tf, idf.to_frame().T)
tfidf = np.multiply(tf, idf)

tfidf

#CONFUSION MATRIX

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Contoh dataframe
df = pd.read_csv('judionlinecleaning4-with-label3.csv')

# Menggunakan TF-IDF Vectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['stemmed_text'])
y = df['label_senti']

# Memisahkan data untuk pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Melatih model
model = MultinomialNB()
model.fit(X_train, y_train)

# Memprediksi dan membuat confusion matrix
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cmd = ConfusionMatrixDisplay(cm, display_labels=[0, 1])

# Menampilkan confusion matrix
cmd.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

#KLASIFIKASI SVM

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from time import time

# Membaca data dari file CSV
df = pd.read_csv('judionlinecleaning4-with-label3.csv')

# Memastikan kolom 'text' adalah string
df['text'] = df['text'].astype(str)

# Inisialisasi objek TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

# Melakukan ekstraksi fitur TF-IDF pada teks
X = tfidf_vectorizer.fit_transform(df['text'])
y = df['label_senti']  # Sesuaikan dengan nama kolom label di dataset Anda

# Membagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Inisialisasi model SVM dengan kernel linear
svm_classifier = SVC(kernel='linear')

# Melatih model SVM
start_time = time()
svm_classifier.fit(X_train, y_train)
training_time_svm = time() - start_time

# Melakukan prediksi pada data uji
start_time = time()
svm_predictions = svm_classifier.predict(X_test)
prediction_time_svm = time() - start_time

print("SVM dengan kernel linear:")
print("Training time:", training_time_svm)
print("Prediction time:", prediction_time_svm)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, roc_auc_score
from time import time

# Membaca data dari file CSV
df = pd.read_csv('judionlinecleaning4-with-label3.csv')

# Memastikan kolom 'text' adalah string
df['text'] = df['text'].astype(str)

# Inisialisasi objek TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

# Melakukan ekstraksi fitur TF-IDF pada teks
X = tfidf_vectorizer.fit_transform(df['text'])
y = df['label_senti']  # Sesuaikan dengan nama kolom label di dataset Anda

# Membagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Inisialisasi model SVM dengan kernel linear
#svm_classifier = SVC(kernel='linear')

# Evaluasi model
accuracy = accuracy_score(y_test, svm_predictions)
recall = recall_score(y_test, svm_predictions, average='weighted')
precision = precision_score(y_test, svm_predictions, average='weighted')
f1 = f1_score(y_test, svm_predictions, average='weighted')

# Menampilkan metrik evaluasi
print("SVM")
print('Accuracy = ', round(accuracy * 100, 2), '%')
print('Recall = ', round(recall * 100, 2), '%')
print('Precision = ', round(precision * 100, 2), '%')
print('F1-Score = ', round(f1 * 100, 2), '%')

# Mengubah label untuk perhitungan ROC AUC (biner)
y_test_binary = (y_test == 1).astype(int)
svm_predictions_binary = (svm_predictions == 1).astype(int)

# Menghitung dan menampilkan ROC AUC
#roc_auc = roc_auc_score(y_test_binary, svm_predictions_binary)
#print('ROC AUC =', roc_auc)

# Menampilkan laporan klasifikasi
print("SVM")
print(classification_report(y_test, svm_predictions))